# This file was *autogenerated* from the file sflash.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1)
reset() # Erase all previously defined variables

load('sflash_keygen.sage')
load('sflash_signature.sage')
###################################################
#                  Initialization                 #
###################################################

if (len( sys.argv ) < _sage_const_1 ):
	print "Operation required\n"
	sys.exit(_sage_const_1 )

op = sys.argv[_sage_const_1 ]
if (op == '-g'):
	#Generate key pair for SFLASH
	dir = sys.argv[_sage_const_2 ]
	os.system("sage sflash_keygen.sage " + dir)
if (op == '-s'):
	#Generate a signature from stored private key
	dir = sys.argv[_sage_const_2 ]
